// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDzyF8zFVXV2KbSoxNC-JubwYQewIjgI',
    appId: '1:214805452047:web:f8e3b62b5f5b07e4a35a7a',
    messagingSenderId: '214805452047',
    projectId: 'customer-app-abhi',
    authDomain: 'customer-app-abhi.firebaseapp.com',
    storageBucket: 'customer-app-abhi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNj1t8Zmo6n5q9I-wlxaJ_Tv0WEwCOdj0',
    appId: '1:214805452047:android:52e418e39ae6ca44a35a7a',
    messagingSenderId: '214805452047',
    projectId: 'customer-app-abhi',
    storageBucket: 'customer-app-abhi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44o_NlH7WArau-BCBa95gf0O7CGvyzwQ',
    appId: '1:214805452047:ios:13a7d46006b88cdaa35a7a',
    messagingSenderId: '214805452047',
    projectId: 'customer-app-abhi',
    storageBucket: 'customer-app-abhi.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA44o_NlH7WArau-BCBa95gf0O7CGvyzwQ',
    appId: '1:214805452047:ios:13a7d46006b88cdaa35a7a',
    messagingSenderId: '214805452047',
    projectId: 'customer-app-abhi',
    storageBucket: 'customer-app-abhi.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChDzyF8zFVXV2KbSoxNC-JubwYQewIjgI',
    appId: '1:214805452047:web:a7cc955c8206bcc2a35a7a',
    messagingSenderId: '214805452047',
    projectId: 'customer-app-abhi',
    authDomain: 'customer-app-abhi.firebaseapp.com',
    storageBucket: 'customer-app-abhi.firebasestorage.app',
  );
}
